#!/usr/bin/env python3
"""
V-Me Apartment Builder — Blender Script
Deterministic Blender scene builder for the default 1-bedroom apartment.

Reads: tools/blender/apartment-data.json (generated by scripts/export-apartment-data.mjs)
Outputs:
  - public/environments/apartment-default/scene.glb (full detail)
  - public/environments/apartment-default/scene.lod-low.glb (merged, low-tier)
  - public/environments/apartment-default/markers.json

Run with:
  blender --background --python tools/blender/build_apartment.py

Ref: Environment Addendum §19.20
"""

import bpy
import bmesh
import json
import os
import math
import mathutils
import sys

DATA_PATH = os.path.join(os.path.dirname(__file__), "apartment-data.json")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "public", "environments", "apartment-default")


def load_data():
    """Load apartment definition from JSON."""
    if not os.path.exists(DATA_PATH):
        print(f"ERROR: {DATA_PATH} not found")
        print("Run: node scripts/export-apartment-data.mjs")
        sys.exit(1)

    with open(DATA_PATH, "r") as f:
        return json.load(f)


def clear_scene():
    """Remove all objects and data from scene."""
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)

    for block_collection in (bpy.data.meshes, bpy.data.materials, bpy.data.lights):
        for block in list(block_collection):
            if block.users == 0:
                block_collection.remove(block)


def hex_to_rgb(hex_str, opacity=1.0):
    """Convert hex color to linear RGB."""
    hex_str = hex_str.lstrip('#')
    r, g, b = (int(hex_str[i:i+2], 16) / 255.0 for i in (0, 2, 4))

    def to_linear(c):
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    return (to_linear(r), to_linear(g), to_linear(b), opacity)


def get_or_create_material(name, hex_color, material_hint=None):
    """Create or retrieve a material."""
    mat = bpy.data.materials.get(name)
    if mat:
        return mat

    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")

    is_glass = material_hint == 'glass'
    bsdf.inputs["Base Color"].default_value = hex_to_rgb(hex_color, 0.35 if is_glass else 1.0)
    bsdf.inputs["Roughness"].default_value = 0.15 if material_hint == 'metal' else (0.05 if is_glass else 0.8)
    bsdf.inputs["Metallic"].default_value = 1.0 if material_hint == 'metal' else 0.0

    if is_glass:
        mat.blend_method = 'BLEND'
        bsdf.inputs["Alpha"].default_value = 0.35

    return mat


def create_box(name, size, position, rotation_y_rad, hex_color, material_hint=None, collection=None, deco=False):
    """Create a box mesh and add to scene."""
    # Note: Blender is Z-up; we convert on export
    bpy.ops.mesh.primitive_cube_add(
        size=1,
        location=(position['x'], -position['z'], position['y'] + size['y']/2)
    )
    obj = bpy.context.active_object
    obj.name = name + ("_deco" if deco else "")
    obj.scale = (size['x']/2, size['z']/2, size['y']/2)
    obj.rotation_euler[2] = -rotation_y_rad

    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    mat = get_or_create_material(f"mat_{hex_color}_{material_hint or 'default'}", hex_color, material_hint)
    obj.data.materials.append(mat)

    if collection:
        for c in obj.users_collection:
            c.objects.unlink(obj)
        collection.objects.link(obj)

    return obj


def create_floor(room, collection):
    """Create floor plane for a room."""
    b = room['bounds']
    bpy.ops.mesh.primitive_plane_add(size=1, location=(b['center']['x'], -b['center']['z'], 0.01))
    obj = bpy.context.active_object
    obj.name = f"floor_{room['id']}"
    obj.scale = (b['halfExtents']['x'], b['halfExtents']['z'], 1)

    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)

    floor_colors = {
        'floor-oak': '#B98A5E',
        'floor-carpet': '#8C7B6B',
        'floor-tile': '#DCE3E6'
    }
    mat = get_or_create_material(f"mat_{room['floorMaterialId']}", floor_colors.get(room['floorMaterialId'], '#CCCCCC'))
    obj.data.materials.append(mat)

    for c in obj.users_collection:
        c.objects.unlink(obj)
    collection.objects.link(obj)


def build_wall_pieces(wall):
    """Compute wall segments (same math as TypeScript)."""
    dx = wall['to']['x'] - wall['from']['x']
    dz = wall['to']['z'] - wall['from']['z']
    length = math.hypot(dx, dz)
    angle = math.atan2(dz, dx)

    segments = []
    current = 0

    for op in sorted(wall['openings'], key=lambda o: o['from']):
        if op['from'] > current:
            seg_len = op['from'] - current
            mid = current + seg_len / 2
            segments.append((mid, seg_len))
        current = op['to']

    if current < length:
        seg_len = length - current
        mid = current + seg_len / 2
        segments.append((mid, seg_len))

    return segments, length, angle, dx, dz


def build_walls(data, collection):
    """Create all wall segments."""
    for wall in data['walls']:
        segments, length, angle, dx, dz = build_wall_pieces(wall)
        for i, (mid, seg_len) in enumerate(segments):
            x = wall['from']['x'] + (dx / length) * mid
            z = wall['from']['z'] + (dz / length) * mid
            create_box(
                f"wall_{wall['id']}_seg{i}",
                {'x': seg_len, 'y': wall['height'], 'z': wall['thickness']},
                {'x': x, 'y': 0, 'z': z},
                angle,
                '#EDE7DD',
                collection=collection,
            )


def build_furniture(data, collection):
    """Create all furniture."""
    for furn in data['furniture']:
        v = furn['visual']
        create_box(
            f"furn_{furn['id']}",
            v['size'],
            v['position'],
            v['rotationY'],
            v['colorHex'],
            material_hint=v.get('materialHint'),
            collection=collection,
            deco=furn.get('decorative', False),
        )


def build_markers(data, collection):
    """Create empty markers for spawn/camera positions."""
    for m in data['markers']:
        # Position empty
        bpy.ops.object.empty_add(
            type='PLAIN_AXES',
            radius=0.15,
            location=(m['position']['x'], -m['position']['z'], m['position']['y'])
        )
        pos_empty = bpy.context.active_object
        pos_empty.name = f"Marker_{m['id']}_Position"

        # Look-at empty
        bpy.ops.object.empty_add(
            type='SPHERE',
            radius=0.05,
            location=(m['lookAt']['x'], -m['lookAt']['z'], m['lookAt']['y'])
        )
        look_empty = bpy.context.active_object
        look_empty.name = f"Marker_{m['id']}_LookAt"

        for e in (pos_empty, look_empty):
            for c in e.users_collection:
                c.objects.unlink(e)
            collection.objects.link(e)


def build_lights(data):
    """Create light objects."""
    for light in data['lights']:
        if light['type'] == 'hemisphere':
            continue  # Runtime adds ambient
        elif light['type'] == 'directional':
            bpy.ops.object.light_add(
                type='SUN',
                location=(light['position']['x'], -light['position']['z'], light['position']['y'])
            )
            obj = bpy.context.active_object
            obj.data.energy = light['intensity'] * 3.0
            if light.get('target'):
                direction = mathutils.Vector((
                    light['target']['x'] - light['position']['x'],
                    -(light['target']['z'] - light['position']['z']),
                    light['target']['y'] - light['position']['y'],
                ))
                obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()
        elif light['type'] == 'point':
            bpy.ops.object.light_add(
                type='POINT',
                location=(light['position']['x'], -light['position']['z'], light['position']['y'])
            )
            obj = bpy.context.active_object
            obj.data.energy = light['intensity'] * 100.0


def merge_for_lod(collection, merged_name):
    """Merge non-decorative furniture for low-tier LOD."""
    bpy.ops.object.select_all(action='DESELECT')
    furn_objs = [o for o in collection.objects if o.name.startswith("furn_") and not o.name.endswith("_deco")]

    if len(furn_objs) < 2:
        return

    for o in furn_objs:
        o.select_set(True)

    bpy.context.view_layer.objects.active = furn_objs[0]
    bpy.ops.object.join()
    bpy.context.active_object.name = merged_name


def export_glb(filepath):
    """Export scene to GLB."""
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.export_scene.gltf(
        filepath=filepath,
        export_format='GLB',
        use_selection=False,
        export_apply=True,
        export_draco_mesh_compression_enable=True,
        export_draco_mesh_compression_level=6,
        export_yup=True,  # glTF convention
        export_lights=True,
        export_cameras=False,
    )


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    data = load_data()
    clear_scene()

    root = bpy.data.collections.new("Apartment")
    bpy.context.scene.collection.children.link(root)

    for room in data['rooms']:
        create_floor(room, root)

    build_walls(data, root)
    build_furniture(data, root)
    build_markers(data, root)
    build_lights(data)

    # Full-detail export
    print(f"Exporting full-detail: {os.path.join(OUT_DIR, 'scene.glb')}")
    export_glb(os.path.join(OUT_DIR, "scene.glb"))

    # Low-tier LOD export
    print(f"Merging furniture for LOD...")
    merge_for_lod(root, "furn_merged_low")
    print(f"Exporting LOD: {os.path.join(OUT_DIR, 'scene.lod-low.glb')}")
    export_glb(os.path.join(OUT_DIR, "scene.lod-low.glb"))

    # Markers sidecar
    markers_out = {m['id']: m for m in data['markers']}
    with open(os.path.join(OUT_DIR, "markers.json"), "w") as f:
        json.dump(markers_out, f, indent=2)

    print(f"✓ Apartment build complete: {OUT_DIR}")


if __name__ == "__main__":
    main()
